apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ✅ This includes PVC, deployments, jobs, etc.
namespace: laravel
resources:
  - ../../base
  
generatorOptions:
  disableNameSuffixHash: true

